/// Flutter icons GobeletDeMerde
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GobeletDeMerde
///      fonts:
///       - asset: fonts/GobeletDeMerde.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GobeletDeMerde {
  GobeletDeMerde._();

  static const _kFontFam = 'GobeletDeMerde';
  static const String? _kFontPkg = null;

  static const IconData image2vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
