/// Flutter icons VerreIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VerreIcons
///      fonts:
///       - asset: fonts/VerreIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class VerreIcons {
  VerreIcons._();

  static const _kFontFam = 'VerreIcons';
  static const String? _kFontPkg = null;

  static const IconData verre = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
